### ISSUE TITLE
Delta94 issue

### ISSUE THREAD

**Issue by TriMontana** [RagePeanut/DeltaE#3]
delta94 does not preclude squareroot operations when "C"  is greater than the pow2 of deltaA and pow2 of deltaB.
when this happens, you will get an overflow because of a squareroot on a potentially large negative number:
suggest: 
    final double deltaH = deltaH1 < 0 ? 0 : sqrt(deltaH1);
and
    return i < 0 ? 0 : sqrt(i);

**Comment by RagePeanut** [comment]
Bit late but, looking into the original JavaScript package this is a port of, I noticed they resolved the same issue about 4 years ago. It was a floating point precision issue. Mirrored the fix in 0.2.1. 

See more: https://github.com/zschuessler/DeltaE/issues/9
